---
- hosts: haproxy
  remote_user: root
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install haproxy
      apt: name=haproxy state=latest

    - name: Enable init script
      replace: dest='/etc/default/haproxy'
             regexp='ENABLED=0'
             replace='ENABLED=1'
             
    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest

    - name: Copy vars file
      copy:
        src: ./vars.yml
        dest: /vars.yml
      become: yes

    - name: Copy task file
      copy:
        src: ./haproxy-apt.yml
        dest: /haproxy-apt.yml
      become: yes

    - name: Copy configuration file
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      become: yes

    - name: Copy handlers file
      copy:
        src: ./handlers.yml
        dest: /handlers.yml
      become: yes

    - name: Copy 49-haproxy file
      copy:
        src: ./49-haproxy.conf
        dest: /etc/rsyslog.d/49-haproxy.conf
      become: yes

    - name: Copy logrotate
      copy:
        src: ./haproxy
        dest: /etc/logrotate.d/haproxy
      become: yes
      
    - name: restart nginx
      apt: name=nginx state=latest

    - name: restart haproxy
      apt: name=haproxy state=latest
