---
- hosts: haproxy
  remote_user: root
  tasks:
    - name: Copy vars file
      copy:
        src: /home/ubuntu/NetworkAutomation/vars.yml
        dest: /vars.yml
      become: yes

    - name: Copy task file
      copy:
        src: /home/ubuntu/NetworkAutomation/haproxy-apt.yml
        dest: /haproxy-apt.yml
      become: yes

    - name: Copy configuration file
      copy:
        src: /home/ubuntu/NetworkAutomation/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      become: yes

    - name: Copy handlers file
      copy:
        src: /home/ubuntu/NetworkAutomation/handlers.yml
        dest: /handlers.yml
      become: yes

    - name: Copy 49-haproxy file
      copy:
        src: /home/ubuntu/NetworkAutomation/49-haproxy.conf
        dest: /etc/rsyslog.d/49-haproxy.conf
      become: yes

    - name: Copy logrotate
      copy:
        src: /home/ubuntu/NetworkAutomation/haproxy
        dest: /etc/logrotate.d/haproxy
      become: yes
