---
#- name: Configurations
- hosts: localhost
  become: yes
  become_method: enable
  user: root

  tasks:
    - name: Call installation file
      shell: ansible-playbook -i /home/ubuntu/NetworkAutomation/hosts /home/ubuntu/NetworkAutomation/installation.yml -b -k
     
