---
#- name: Configurations
- user: root
  become: yes
  become_method: enable
  hosts: localhost

  tasks:
    - name: Finding file paths
      find:
         paths: /home
         patterns: "hosts"
      register: files_found
      find:
         paths: /home
         patterns: "installation.yml"
      register: ins_file
      find:
         paths: /home
         patterns: "proxyins.yml"
      register: proxy_file
      find:
         paths: /home
         patterns: "haproxy.yml"
      register: func_file

    - name: Call installation file
      shell: ansible-playbook -i ./hosts ./installation.yml -b -k
      become: yes
  
    - name: Call proxyins file
      shell: ansible-playbook -i ./hosts ./proxyins.yml -b -k  
      become: yes
  
    - name: Call haproxy file
      shell: ansible-playbook -i ./hosts ./haproxy.yml -b -k
      become: yes  
