---
#- name: Configurations
- user: root
  become: yes
  become_method: enable
  hosts: localhost

  tasks:
    - name: Call installation file
      command: "ansible-playbook -i ~/NetworkAutomation/hosts ~/NetworkAutomation/installation.yml -b -k"
      become: yes
  
    - name: Call proxyins file
      shell: ansible-playbook -i ~/NetworkAutomation/hosts ~/NetworkAutomation/proxyins.yml -b -k  
      become: yes
  
    - name: Call function file
      shell: ansible-playbook -i ~/NetworkAutomation/hosts ~/NetworkAutomation/function.yml -b -k
      become: yes  
